[build]
  base = "."                   # Ensure the base directory is the root of the repo
  command = ""                  # No build command, since it's a static site
  publish = "Groceryhub"        # This is the directory with your site files

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
