[build]
  base = "Groceryhub"              # The source directory for your project
  command = "npm run build"        # Replace with your actual build command if needed
  publish = "Groceryhub"           # The directory to publish after the build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
