[build]
  publish = "Groceryhub"   # This points to the folder containing your static assets.
  command = ""             # No build step needed as you're not using a build tool.

[[redirects]]
  from = "/*"
  to = "/index.html"      # This ensures all routes redirect to index.html.
  status = 200
