[build]
  base = "src/Groceryhub"           # Set this to the directory containing package.json
  command = "npm run build"         # Ensure this command works
  publish = "src/Groceryhub/build"  # Specify the output directory after the build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
