[build]
  base = "."                      # This sets the root directory as the base for the build
  command = "npm run build"        # Replace this with your build command, or leave it empty if you don’t have one
  publish = "Groceryhub"           # This points to the directory that should be served after build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
